### ISSUE TITLE
todo List

### ISSUE THREAD

**Issue by pei-lu** [HenoHyj/ECE196-Team-14#2]
- [x]  Assemble the BNO shield for the dev board.
- [x]  Update the website.
- [x] 3D print the case for the speaker and main BNO motion sensor.
- [x] Wednesday, Week 7: 3D print the case to secure the secondary BNO on the lock.
- [x] friday, Week 7: update the poster
- [x] Monday, Week 8: Read accelerometer data from the BNO and calculate the shifted distance of the chip.
- [x] Wednesday, Week 8: Calculate the distance between the two IMUs and find suitable calibration intervals.
- [x] Friday, Week 8: Use the breakout board to play the pre-recorded audio.
- [ ] Wednesday, Week 9: Test and determine an appropriate trigger distance to activate the audio alert.
- [ ] Friday, Week 9: Integrate an ESP32-CAM into the system to capture images of suspects during abnormal vibrations. Draft the outline for the ESP32-CAM and BNO documentation.
- [ ] Monday, Week 10: Record video clips for the final presentation and finalize documentation.
- [ ] Wednesday, Week 10: Edit the video and resolve any remaining system bugs.

**Comment by pei-lu** [comment]
new to do list
箭头是有意义的，返回去check一下
[ ]block diagram--only for hardware, 主要只有硬件的构架 ，如何连接（）不需要硬件之间的交互逻辑  
[ ]specify what chip it is
